name: SamOSv2
options:
  bundleIdPrefix: com.samosv2
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "16.0"
  minimumXcodeGenVersion: "2.40.0"

settings:
  base:
    SWIFT_VERSION: "5.9"
    MACOSX_DEPLOYMENT_TARGET: "14.0"

targets:
  SamOSv2:
    type: application
    platform: macOS
    sources:
      - path: SamOSv2
        excludes:
          - "Vendor/Porcupine/include/**"
          - "Vendor/Porcupine/lib/**"
          - "Vendor/Porcupine/resources/**"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.samosv2.SamOSv2
        INFOPLIST_KEY_NSMicrophoneUsageDescription: "Sam needs microphone access for voice commands"
        INFOPLIST_KEY_NSCameraUsageDescription: "Sam needs camera access for visual features"
        INFOPLIST_KEY_NSSpeechRecognitionUsageDescription: "Sam needs speech recognition for voice commands"
        PRODUCT_NAME: SamOSv2
        GENERATE_INFOPLIST_FILE: YES
        CURRENT_PROJECT_VERSION: 1
        MARKETING_VERSION: "2.0.0"
        SWIFT_INCLUDE_PATHS: "$(SRCROOT)/SamOSv2/Vendor/Porcupine/include"
        LIBRARY_SEARCH_PATHS: "$(SRCROOT)/SamOSv2/Vendor/Porcupine/lib"
        OTHER_LDFLAGS: "-lpv_porcupine"
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/../Frameworks"
    postBuildScripts:
      - script: |
          mkdir -p "${BUILT_PRODUCTS_DIR}/${FRAMEWORKS_FOLDER_PATH}"
          cp "${SRCROOT}/SamOSv2/Vendor/Porcupine/lib/libpv_porcupine.dylib" "${BUILT_PRODUCTS_DIR}/${FRAMEWORKS_FOLDER_PATH}/"
        name: "Embed Porcupine dylib"
    entitlements:
      path: SamOSv2/SamOSv2.entitlements
      properties:
        com.apple.security.app-sandbox: true
        com.apple.security.device.audio-input: true
        com.apple.security.device.camera: true
        com.apple.security.network.client: true
        com.apple.security.files.user-selected.read-write: true

  SamOSv2Tests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - SamOSv2Tests
    dependencies:
      - target: SamOSv2
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.samosv2.SamOSv2Tests
        GENERATE_INFOPLIST_FILE: YES
        SWIFT_INCLUDE_PATHS: "$(SRCROOT)/SamOSv2/Vendor/Porcupine/include"
        LIBRARY_SEARCH_PATHS: "$(SRCROOT)/SamOSv2/Vendor/Porcupine/lib"
